### ISSUE TITLE
TPU support question

### ISSUE THREAD

**Issue by Zurnaz** [davisyoshida/jax-gptq#1]
Hi, cool repo!

I'm looking to run inference on gptq quantized models on TPU. 

Is this implementation strictly GPU based or would it be possible for me to try modify it support TPUs?

**Comment by davisyoshida** [comment]
Thanks! I've only tested it on GPUs but you should be able to just replace the GPU references with TPUs. If you're running a model which needs to use multiple TPUs then it'll be nontrivial though, since `quantize` is basically doing manual memory management to keep GPU memory usage low.

**Comment by Zurnaz** [comment]
Thanks for getting back!

Technically it is one physical TPU but yes as an end goal I'm aiming to shard across the 8 TPU cores. I've worked with another library that shards transformer layers and so my next step to get better grasp of GPTQ.

For now I'll give the simpler version a try. 

I'll close this issue since my question is answered. Thanks Again!

**Comment by davisyoshida** [comment]
@Zurnaz Unless your model is massive 1 TPU should probably be enough to quantize it. The `quantize` transform only loads one layer into VRAM at once.
